### ISSUE TITLE
[BUG] Quick replies disappear without sending the message

### ISSUE THREAD

**Issue by dlassalle** [WideChat/Rocket.Chat.Livechat#19]
Unsure of what recent change did this, i imagine its a quick fix for someone who knows the language better

**Comment by dlassalle** [comment]
@Shailesh351 with the release of UIKit, we may need to re-implement quick-replies anyway using that
https://github.com/RocketChat/Rocket.Chat.Livechat/pull/474

**Comment by dlassalle** [comment]
In fact, im going to close this and re-open once quick-replies are updated in the app that provides these

**Comment by Shailesh351** [comment]
Okay @dlassalle. This bug is because of new default avatar setting. 
Here https://github.com/shubhsherl/Rocket.Chat/blob/0034826d254ee133960544f68e03444ab71bab28/app/livechat/server/api/v1/message.js#L21 `livechat/message` API makes avatar as mandatory payload `avatar: String,`.

We need to replace it with `avatar: Match.Optional(String),` to make it optional.
