### ISSUE TITLE
[BUG] Skip registration by domain not wokring

### ISSUE THREAD

**Issue by dlassalle** [WideChat/Rocket.Chat.Livechat#41]
> Im trying to get 'livechat.viasatconnect.com/livechat' to show the reg page, but skip it on localhost

In this case you can only mention localhost in the list, so it will only skip on localhost.

From the PR 381:
Adding only domain name skips registration for all paths with that domain
i.e. if www.google.com it will skip for www.google.com/a,www.google.com/b, www.google.com/*
Adding specific path like www.google.com/a will only skip registration on that path not others

_Originally posted by @Shailesh351 in https://github.com/WideChat/Rocket.Chat.Livechat/pull/39#issuecomment-702181418_

**Comment by dlassalle** [comment]
@Shailesh351 i tried hosting the widget on different pages, but none of them work except for skipping 'livechat.viasatconnect.com', but when doing that it skips the registration for ALL pages

**Comment by shubhsherl** [comment]
@dlassalle when we use LiveChat with `Livechat Script` on any test webpage, the url is same what we pass in the script function. For example: 
```
<!-- Start of Rocket.Chat Livechat Script -->
	<script type="text/javascript">
	(function(w, d, s, u) {
		w.RocketChat = function(c) { w.RocketChat._.push(c) }; w.RocketChat._ = []; w.RocketChat.url = u;
		var h = d.getElementsByTagName(s)[0], j = d.createElement(s);
		j.async = true; j.src = 'https://livechat.viasatconnect.com/livechat/rocketchat-livechat.min.js';
		h.parentNode.insertBefore(j, h);
	})(window, document, 'script', 'https://livechat.viasatconnect.com/livechat');
	</script>
```
Using the above script on any page say 'example.com', on the serverside will recieve the url `https://livechat.viasatconnect.com/livechat` not 'example.com'. That's why when you were skipping 'livechat.viasatconnect.com', it was skiping ALL pages using the above script.

**Comment by shubhsherl** [comment]
@dlassalle One solution can be to add query params in the URL and skipDomainList, and check that as well with hostname and path. 
@Shailesh351 Thoughts?

**Comment by Shailesh351** [comment]
> @dlassalle One solution can be to add query params in the URL and skipDomainList, and check that as well with hostname and path.
> @Shailesh351 Thoughts?

@shubhsherl As our widget is loading in iFrame and the src of iFrame is `https://livechat.viasatconnect.com/livechat`. So
window.location.href uses that instead of actual web page url. https://github.com/WideChat/Rocket.Chat.Livechat/pull/20/files#diff-dbd1065ebaf59b9c5fec54631b2e5e06R23

I'm trying to find a way using which we can pass actual parent web page url down to iFrame and pass it on with `Livechat.config()` API

**Comment by ear-dev** [comment]
PR #43
